"""core/execution — 执行层（dispatch、finalize、worker 池）。"""
from __future__ import annotations

from core.contracts.execution import action_key_param
from core.execution.helpers import (
    _classify_durable_failure,
    _load_durable_failure_policy,
    _normalize_tool_result_text_fields,
    _run_progress_text,
    _run_status_from_result,
    _tool_result_log_fields,
    build_meta_reflection,
    finalize_run,
    record_meta_reflection_memory,
    record_run_outcome_memory,
)
from core.execution.run_profile import (
    ExecutionProfile,
    RunProfile,
    RunTypeProfile,
    resolve_default_tier_for_run_type,
    RUN_TYPE_PROFILES,
    KNOWN_RUN_TYPES,
    RUN_TYPE_EVOLUTION,
    RUN_TYPE_EXEC,
    RUN_TYPE_LLM,
    RUN_TYPE_CHAT_REPLY,
    RUN_TYPE_MULTIMODAL,
    RUN_TYPE_SUBAGENT,
    RUN_TYPE_JUDGE,
    RUN_TYPE_PROBE,
    RUN_TYPE_TOOL_CHAIN,
    WORKER_LIMIT_DEFAULT_KEY,
    WORKER_EVOLVE,
    WORKER_EXEC,
    WORKER_LLM,
    WORKER_MULTIMODAL,
    WORKER_SUBAGENT,
    WORKER_TOOL_CHAIN,
    run_type_profile,
    resolve_execution_profile,
    resolve_execution_dispatch,
    iter_run_profiles,
    infer_run_profile,
    worker_type_for_run_type,
    RUN_TYPE_DEFAULT_TIER,
    TASK_DEFAULT_TIER,
)
from core.execution.routing import resolve_run_type_routing
from core.execution.layer import ExecutionLayer
from core.execution.workers import WorkerLayer

_infer_run_profile = infer_run_profile

__all__ = [
    "ExecutionLayer",
    "WorkerLayer",
    "_classify_durable_failure",
    "_infer_run_profile",
    "_load_durable_failure_policy",
    "_normalize_tool_result_text_fields",
    "_run_progress_text",
    "_run_status_from_result",
    "_tool_result_log_fields",
    "RUN_TYPE_EVOLUTION",
    "RUN_TYPE_EXEC",
    "RUN_TYPE_LLM",
    "RUN_TYPE_MULTIMODAL",
    "RUN_TYPE_CHAT_REPLY",
    "RUN_TYPE_SUBAGENT",
    "RUN_TYPE_JUDGE",
    "RUN_TYPE_PROBE",
    "RUN_TYPE_TOOL_CHAIN",
    "KNOWN_RUN_TYPES",
    "RUN_TYPE_DEFAULT_TIER",
    "TASK_DEFAULT_TIER",
    "action_key_param",
    "WORKER_EVOLVE",
    "WORKER_EXEC",
    "WORKER_LLM",
    "WORKER_LIMIT_DEFAULT_KEY",
    "WORKER_MULTIMODAL",
    "WORKER_SUBAGENT",
    "WORKER_TOOL_CHAIN",
    "worker_type_for_run_type",
    "resolve_default_tier_for_run_type",
    "resolve_run_type_routing",
    "ExecutionProfile",
    "RunProfile",
    "RunTypeProfile",
    "RUN_TYPE_PROFILES",
    "run_type_profile",
    "iter_run_profiles",
    "resolve_execution_dispatch",
    "resolve_execution_profile",
    "infer_run_profile",
    "build_meta_reflection",
    "finalize_run",
    "record_meta_reflection_memory",
    "record_run_outcome_memory",
]
